### ISSUE TITLE
Font Awesome Shortcode Issue with Brand Icons

### ISSUE THREAD

**Issue by terencehoverter** [chrisblakley/Nebula#1693]
I had some issues with using the Font Awesome Shortcode, but mostly when using the brand icons. I tried a couple of different ways to get it working but no luck. Here are some examples of what I tried.

Input:
```[icon type=fab-facebook-square]```
Outputs:
```<i class=" nebula-icon-shortcode fas fa-fw fa-fab-facebook-square"></i>```

Input:
```[icon type=facebook-square  class="fab"] ```
Outputs:
```<i class="fab nebula-icon-shortcode fas fa-fw fa-facebook-square"></i>```

**Comment by chrisblakley** [comment]
I've got this updated. It was due to the 4 different styles provided in FA5. The provided code that Nebula dumps into the WYSIWYG actually had a syntax error, so your first input wouldn't have worked either way, so I've fixed that too.

FA calls them "styles", but to avoid confusion with inline styling provided by other shortcodes I called the new parameter `mode` which defaults to `fas`. It accepts `fas`, `s`, or `solid` for any of the FA styles.

**Some example usage:**
`[icon mode=fab type=fa-facebook-square]`
`[icon mode=brand type=fa-facebook-square]`
`[icon mode=b type=fa-facebook-square]`
`[icon mode=fas type=fa-home]`
`[icon type=fa-home] //Defaults to solid`
`[icon mode=regular type=fa-home]`
`[icon mode=l type=fa-home]`

**Comment by terencehoverter** [comment]
Still having issues with this one....

**Shortcode Used:**
```[icon type=fa-youtube-square class=fab color=#ff7700 size=75px]```

**Desired Outcome:**
```html
<i class="fab nebula-icon-shortcode fa-fw fa-youtube-square" style="color:#ff7700;font-size:75px;"></i>
```

**Actual Outcome:**
```html
<i class="fab nebula-icon-shortcode fas fa-fw fa-youtube-square" style="color:#ff7700;font-size:75px;"></i>
```
**Useless pic of it not working:**
![image](https://user-images.githubusercontent.com/30500449/41921233-66b64532-7930-11e8-82d3-4beb6724ceb6.png)

From what I understand, the issue stems from trying to determine what Font Awesome Font needs to be applied. Can we adjust the shortcode to accept an additional parameter which declares the font instead of trying to determine which one to use?

**Comment by terencehoverter** [comment]
Wow! You really future proofed this one.

The paramater my shortcode was missing was mode, see below for correct usage:
`[icon type=fa-youtube-square mode=brand color=#ff7700 size=75px]`
